### ISSUE TITLE
Add Import qualifiers to StatusQ.Core.Utils and StatusQ.Core.Theme as file Utils.qml silently conflicts with Uitls.qml from imports/utils

### ISSUE THREAD

**Issue by Seitseman** [status-im/status-desktop#15563]
# Bug Report

## Description

During investigation of issue #15479 it was discovered that importing of QML modules that have identical component names (QML basefilenames) will result in "silent" runtime errors, e.g., function not available. For example `TypeError: Property 'getColorForId' of object Utils_QMLTYPE_148(0x2f41f100) is not a function` . 

## Steps to reproduce

If particular qml component imports two modules that have identically named subcomponents, it seems that the last import will overwrite already loaded component with its own version.

#### Expected behavior
All module component conflicts should be resolved by introducing "qualified" imports:
https://doc.qt.io/qt-5/qtqml-syntax-imports.html#module-namespace-imports

### Additional Information

- Status desktop version: 2.29
- Operating System: ALL
