### ISSUE TITLE
CI builds for macOS app M1

### ISSUE THREAD

**Issue by alexjba** [status-im/status-desktop#9984]
## Description

We've added support for arm64 builds in this PR https://github.com/status-im/status-desktop/pull/9869
The app can be compiled natively on M1 chips following these steps:
1. `make clean`
2. `brew install qt@5`
3. update `QTDIR` and `PATH` and point to a Qt installation for arm64
4. `make`

The next step is to add the M1 builds in the CI process and to be able to release them.

**Comment by jakubgs** [comment]
When do we need this?

**Comment by alexjba** [comment]
@John-44 @iurimatias 

> When do we need this?

**Comment by John-44** [comment]
> @John-44 @iurimatias
> 
> > When do we need this?

Ideally, it would be great if we could have an OSX ARM build of 0.11 that folks could download, because the biggest issue so far with dogfooding is Status Desktop's performance, which is particularly bad on OSX ARM hardware today.  For Mac users, native Apple ARM builds give a good perf. improvement.

So re. when do we need this, the 0.11 target release date is Friday 31st March.   So (if possible) it would be great to have this by Friday 31st March at the latest.

**Comment by jakubgs** [comment]
I'm back from holidays on the 3rd. This in THEORY should be simple, so I can probably make that deadline.

Probably.

**Comment by jakubgs** [comment]
One matter is that the setup script for MacOS hosts needs support for ARM64 Qt:
https://github.com/status-im/status-desktop/blob/3008e56455bfae838105dc8f2bc11f9db62d9a32/scripts/macos_build_setup.sh#L26
But we already have it covered for Go:
https://github.com/status-im/status-desktop/blob/3008e56455bfae838105dc8f2bc11f9db62d9a32/scripts/macos_build_setup.sh#L43-L47

**Comment by jakubgs** [comment]
But it appears that the only Qt architecture available via `aqtinstall` is:
```
 > aqt list-qt mac desktop --arch 5.15.2
clang_64 wasm_32
```
Not sure if that matters for this case. It could cover ARM64 too.

**Comment by jakubgs** [comment]
@alexjba did you not have to install Qt via some other method instead of `aqt` to make this work on M1? Or does that work fine?

**Comment by alexjba** [comment]
> @alexjba did you not have to install Qt via some other method instead of `aqt` to make this work on M1? Or does that work fine?

`brew install qt@5` will install the arm version

**Comment by jakubgs** [comment]
That's not really a solution.
We need to pin a specific version of Qt so we don't get hard to debug issues die to version mismatches.

**Comment by jakubgs** [comment]
The `qt@5` version is actually `5.15.8`, which is different from the `5.15.2` we use:
https://github.com/Homebrew/homebrew-core/blob/fdd37018b9a77ae893b86f8d24d0934f42f1a33b/Formula/qt%405.rb#L6

So that's an issue.

**Comment by caybro** [comment]
> The `qt@5` version is actually `5.15.8`, which is different from the `5.15.2` we use: https://github.com/Homebrew/homebrew-core/blob/fdd37018b9a77ae893b86f8d24d0934f42f1a33b/Formula/qt%405.rb#L6
> 
> So that's an issue. This will not be simple.

Can't we actually use 5.15.8 for both archs on macOS?

**Comment by jakubgs** [comment]
That's a good question, I don't know. Can we? I have no idea how big the differences are, I've never used Qt for anything.

**Comment by caybro** [comment]
Heck, we could even use the brew Qt5 build for Linux (sorry Windows users :)

**Comment by jakubgs** [comment]
Although the other issue is that even if we do switch to `5.15.8` we cannot rely on Brew to provide exactly the same version forever.

**Comment by caybro** [comment]
> Although the other issue is that even if we do switch to `5.15.8` we cannot rely on Brew to provide exactly the same version forever.
> 

That should not be a problem, all 5.15.x are binary/backwards compatible

**Comment by alexjba** [comment]
on linux we're stuck on Qt5.15.2 because of the glibc version. Migrating to a brew installation of qt5.15.8 means to upgrade the minimum requirements on linux.

**Comment by alexjba** [comment]
> > The `qt@5` version is actually `5.15.8`, which is different from the `5.15.2` we use: https://github.com/Homebrew/homebrew-core/blob/fdd37018b9a77ae893b86f8d24d0934f42f1a33b/Formula/qt%405.rb#L6
> > So that's an issue. This will not be simple.
> 
> Can't we actually use 5.15.8 for both archs on macOS?

This is a good option IMO

**Comment by jakubgs** [comment]
Well, if we are confident about higher minor verisons of `5.15.x` being fine for macOS then we can use that solution.

But I probably can't implement this until I'm back from my ski trip on the 3rd of April.

**Comment by jakubgs** [comment]
We could easily use Nix for macOS builds on both architectures. Nixpkgs already has `5.15.8`:
https://github.com/NixOS/nixpkgs/blob/98df3b1874578b41650528a63827412e8c960875/pkgs/development/libraries/qt-5/5.15/srcs.nix#L4

And I do have a branch with a `shell.nix` ready:
https://github.com/status-im/status-desktop/blob/9bdd84cd20abef628d9f7eccdb817e728c986646/shell.nix#L1-L40
I'd rather use it for all builds, but we could use it just for macOS for now.

**Comment by caybro** [comment]
Yeah, either use Nix or brew to get the ARM support, it doesn't matter we'll have a greater minor version there (5.15.8 vs 5.15.2 elsewhere; I'm running 5.15.8 locally too on Linux)

**Comment by jakubgs** [comment]
What the hell happened here? Why do we have two `vendor` locations?
https://github.com/status-im/status-desktop/blob/9af1734c6a62d80b68445b071bab984c43ada2f5/.gitmodules#L117-L119

**Comment by caybro** [comment]
> What the hell happened here? Why do we have two `vendor` locations?
> 
> https://github.com/status-im/status-desktop/blob/9af1734c6a62d80b68445b071bab984c43ada2f5/.gitmodules#L117-L119

It's just a submodule of StatusQ; @igor-sirotin

**Comment by jakubgs** [comment]
Wtf:
https://github.com/status-im/status-desktop/blob/9af1734c6a62d80b68445b071bab984c43ada2f5/.gitmodules#L111-L113
This is clearly wrong.

**Comment by jakubgs** [comment]
What is happening here...
```
 > grep SortFilterProxyModel .gitmodules   
[submodule "vendor/SortFilterProxyModel"]
	path = ui/StatusQ/vendor/SortFilterProxyModel
	url = https://github.com/status-im/SortFilterProxyModel.git

 > cat ui/StatusQ/.gitmodules
[submodule "vendor/SortFilterProxyModel"]
	path = vendor/SortFilterProxyModel
	url = https://github.com/status-im/SortFilterProxyModel.git
```
Why would there be tro `.gitmodules` files with the same entry.

**Comment by caybro** [comment]
I think those are leftovers from when StatusQ used to be a submodule itself too; does this happen on a fresh checkout?

**Comment by jakubgs** [comment]
Classic yak shaving. I work on one thing and discover some completely unrelated chaos that needs fixing.

**Comment by jakubgs** [comment]
Fix for the submodule mess:

* https://github.com/status-im/status-desktop/pull/9993

**Comment by anastasiyaig** [comment]
@jakubgs hey there! Can u please take a look into this one this week?

**Comment by jakubgs** [comment]
Yes. I can. I had to catch up with a lot of stuff from when I was on holiday. I will attempt to use Nix shell to provide QT for both `x86_74` and `aarch64` build on Macs. This will mean using Qt 5.15.8, but it will not have the same issue as Linux with `glibc`.

**Comment by jakubgs** [comment]
Oh for fuck's sake:
```nix
    # qtwebengine-5.15.8: "QtWebEngine can only be built for x86,
    # x86-64, ARM, Aarch64, and MIPSel architectures."
    platforms =
      lib.trivial.pipe lib.systems.doubles.all [
        (map (double: lib.systems.elaborate { system = double; }))
        (lib.lists.filter (parsedPlatform: with parsedPlatform;
          isUnix &&
          (isx86_32  ||
           isx86_64  ||
           isAarch32 ||
           isAarch64 ||
           (isMips && isLittleEndian))))
        (map (plat: plat.system))
      ];
    broken = stdenv.isDarwin && stdenv.isx86_64;
```
https://github.com/NixOS/nixpkgs/blob/e3652e0735fbec227f342712f180f4f21f0594f2/pkgs/development/libraries/qt-5/modules/qtwebengine.nix#L235-L249

We can't install `qtwebengine` on MacOS `x86_64`.

It's always something.

**Comment by jakubgs** [comment]
Why would we need two installations?

**Comment by alexjba** [comment]
> Why would we need two installations?

To install Qt on both arch? But if we don't, that's even better! 😄

**Comment by jakubgs** [comment]
I don't get it. We have both i7 and M1 Macs. I don't get why we would need different brew installations.

Also, I can still use Nix for `aarch64`, I just can't for `x86_64`, which is annoying.

**Comment by jakubgs** [comment]
And indeed the Qt custom build does fail when I attempt to ignore the `broken` attribute:
```
/nix/store/v6v5w24j3xdw78smv6vfwld784yj704w-apple-framework-CoreFoundation-11.0.0/Library/Frameworks/CoreFoundation.framework/Headers/CFURL.h:1189:83: error: expected ','
    kCFURLBookmarkCreationWithSecurityScope API_AVAILABLE(macos(10.7), macCatalyst(13.0))  API_UNAVAILABLE(ios, watchos, tvos) = ( 1UL << 11 ), // Mac OS X 10.7.3 and later, include information in the bookmark data which allows the same sandboxed process to access the resource after being relaunched
                                                                                  ^
/nix/store/v6v5w24j3xdw78smv6vfwld784yj704w-apple-framework-CoreFoundation-11.0.0/Library/Frameworks/CoreFoundation.framework/Headers/CFURL.h:1190:98: error: expected ','
    kCFURLBookmarkCreationSecurityScopeAllowOnlyReadAccess API_AVAILABLE(macos(10.7), macCatalyst(13.0)) API_UNAVAILABLE(ios, watchos, tvos) = ( 1UL << 12 ), // Mac OS X 10.7.3 and later, if used with kCFURLBookmarkCreationWithSecurityScope, at resolution time only read access to the resource will be granted
                                                                                                 ^
/nix/store/v6v5w24j3xdw78smv6vfwld784yj704w-apple-framework-CoreFoundation-11.0.0/Library/Frameworks/CoreFoundation.framework/Headers/CFURL.h:1200:85: error: expected ','
    kCFURLBookmarkResolutionWithSecurityScope API_AVAILABLE(macos(10.7), macCatalyst(13.0)) API_UNAVAILABLE(ios, watchos, tvos) = ( 1UL << 10 ), // Mac OS X 10.7.3 and later, use the secure information included at creation time to provide the ability to access the resource in a sandboxed process.
                                                                                    ^
3 errors generated.
[21/187] CXX base/strings/string_number_conversions.o
ninja: build stopped: subcommand failed.
Project ERROR: GN build error!
make[2]: *** [Makefile:65: sub-gn-pro-make_first] Error 3
make[2]: Leaving directory '/private/tmp/nix-build-qtwebengine-5.15.12.drv-0/source/src/buildtools'
make[1]: *** [Makefile:58: sub-buildtools-make_first] Error 2
make[1]: Leaving directory '/private/tmp/nix-build-qtwebengine-5.15.12.drv-0/source/src'
make: *** [Makefile:52: sub-src-make_first] Error 2
error: builder for '/nix/store/07c5vnqgz2iixmp842c1bz427q41626p-qtwebengine-5.15.12.drv' failed with exit code 2;
```

**Comment by caybro** [comment]
It looks the maximum supported macOS version is (for some reason?) `macCatalyst(13.0)`. What version do we have when building this?

**Comment by jakubgs** [comment]
All of our CI hosts are running some version of macOS 13:
```
 > a ci-slave-macos -o -a 'system_profiler SPSoftwareDataType | grep "System Version"'
macm1-01.he-eu-fsn1.ci.devel | CHANGED | rc=0 | (stdout)       System Version: macOS 13.1 (22C65)
macm1-02.he-eu-fsn1.ci.devel | CHANGED | rc=0 | (stdout)       System Version: macOS 13.0 (22A380)
maci7-03.ms-eu-dublin.ci.devel | CHANGED | rc=0 | (stdout)       System Version: macOS 13.1 (22C65)
maci7-02.ms-eu-dublin.ci.devel | CHANGED | rc=0 | (stdout)       System Version: macOS 13.1 (22C65)
maci7-01.ms-eu-dublin.ci.devel | CHANGED | rc=0 | (stdout)       System Version: macOS 13.2 (22D49)
macm1-01.ih-eu-mda1.ci.devel | CHANGED | rc=0 | (stdout)       System Version: macOS 13.2.1 (22D68)
```

**Comment by jakubgs** [comment]
Actually, the most recent hotfix release of Qt 5.15 is 5.15.13:
https://www.qt.io/blog/commercial-lts-qt-5.15.13-released

I wonder if I upgrade xcode to a newer Qt than 5.15.8 it would work on macOS higher than 13.0.

**Comment by caybro** [comment]
> Actually, the most recent hotfix release of Qt 5.15 is 5.15.13: https://www.qt.io/blog/commercial-lts-qt-5.15.13-released
> 
> I wonder if I upgrade xcode to a newer Qt than 5.15.8 it would work on macOS higher than 13.0.

It can't be worse :)

**Comment by jakubgs** [comment]
Hm, but that constraint is actually coming from `framework-CoreFoundation`, so I don't think Qt or QtWebEngine version matters.

**Comment by jakubgs** [comment]
Current `master` of `nixpkgs` provides only two versions of Apple SDK:
```nix
  # macOS 10.12 SDK
  apple_sdk_10_12 = pkgs.callPackage ../os-specific/darwin/apple-sdk {
    inherit (buildPackages.darwin) print-reexports;
    inherit (self) darwin-stubs;
  };

  # macOS 11.0 SDK
  apple_sdk_11_0 = pkgs.callPackage ../os-specific/darwin/apple-sdk-11.0 { };

  # Pick an SDK
  apple_sdk = if stdenv.hostPlatform.isAarch64 then apple_sdk_11_0 else apple_sdk_10_12;
```
https://github.com/NixOS/nixpkgs/blob/4116178905c9a81d900074fdf17e34b54a3b8e65/pkgs/top-level/darwin-packages.nix#L27-L37

And we are already using the `11.0` version available.

**Comment by jakubgs** [comment]
That's something new:
```
Building: status-go
# github.com/rjeczalik/notify
vendor/github.com/rjeczalik/notify/watcher_fsevents_cgo.go:10:10: fatal error: CoreServices/CoreServices.h: No such file or directory
   10 | #include <CoreServices/CoreServices.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

**Comment by jakubgs** [comment]
Using Nix might require too much work right now. I think I'll just to the simple solution for now using Brew:
```
admin@macm1-01.he-eu-fsn1.ci.devel:~ % brew install qt@5   
...
If you need to have qt@5 first in your PATH, run:
  echo 'export PATH="/opt/homebrew/opt/qt@5/bin:$PATH"' >> ~/.zshrc

For compilers to find qt@5 you may need to set:
  export LDFLAGS="-L/opt/homebrew/opt/qt@5/lib"
  export CPPFLAGS="-I/opt/homebrew/opt/qt@5/include"

For pkg-config to find qt@5 you may need to set:
  export PKG_CONFIG_PATH="/opt/homebrew/opt/qt@5/lib/pkgconfig"

admin@macm1-01.he-eu-fsn1.ci.devel:~ % ls -l /opt/homebrew/opt/qt@5/                  
total 480
drwxr-xr-x   79 admin  wheel   2528 Nov 12 22:00 Frameworks
-rw-r--r--    1 admin  wheel   5111 Apr  6 11:13 INSTALL_RECEIPT.json
-rw-r--r--    1 admin  wheel  22961 Nov 12 22:00 LICENSE.FDL
-rw-r--r--    1 admin  wheel  36363 Nov 12 22:00 LICENSE.GPL3-EXCEPT
-rw-r--r--    1 admin  wheel  15351 Nov 12 22:00 LICENSE.GPLv2
-rw-r--r--    1 admin  wheel  35641 Nov 12 22:00 LICENSE.GPLv3
-rw-r--r--    1 admin  wheel  26828 Nov 12 22:00 LICENSE.LGPLv21
-rw-r--r--    1 admin  wheel   8174 Nov 12 22:00 LICENSE.LGPLv3
-rw-r--r--    1 admin  wheel  78091 Nov 12 22:00 LICENSE.QT-LICENSE-AGREEMENT
-rw-r--r--    1 admin  wheel   3842 Nov 12 22:00 README
drwxr-xr-x   50 admin  wheel   1600 Apr  6 11:13 bin
drwxr-xr-x    4 admin  wheel    128 Nov 12 22:00 doc
drwxr-xr-x   95 admin  wheel   3040 Nov 12 22:00 include
drwxr-xr-x  119 admin  wheel   3808 Apr  6 11:13 lib
drwxr-xr-x    8 admin  wheel    256 Nov 12 22:00 libexec
drwxr-xr-x   79 admin  wheel   2528 Apr  6 11:13 mkspecs
drwxr-xr-x   15 admin  wheel    480 Nov 12 22:00 phrasebooks
drwxr-xr-x   31 admin  wheel    992 Nov 12 22:00 plugins
drwxr-xr-x   28 admin  wheel    896 Nov 12 22:00 qml
drwxr-xr-x  347 admin  wheel  11104 Nov 12 22:00 translations
```

**Comment by jakubgs** [comment]
Looks like it does indeed work:

* https://ci.status.im/job/status-desktop/job/branches/job/macos/job/aarch64/job/PR-10210/2/
* https://status-im-desktop-prs.ams3.digitaloceanspaces.com/StatusIm-Desktop-230406-115113-fe830c-pr10210.dmg

Could @anastasiyaig or @glitchminer try it out to see if it works correctly.

I will need to add architecture to filename.

**Comment by glitchminer** [comment]
Looks good @jakubgs , launched and created an account OK.

![image](https://user-images.githubusercontent.com/50769329/230377592-6ae4f6bd-c37b-48bc-981e-6284533a0819.png)

**Comment by anastasiyaig** [comment]
it works to me as well , thanks @jakubgs , great job!

**Comment by anastasiyaig** [comment]
@jakubgs anything else is pending to close this task? Perhaps something from dev team on desktop?

**Comment by jakubgs** [comment]
Yes, the PR:

* https://github.com/status-im/status-desktop/pull/10210

I finally got a review 20 minutes ago for it. There's some work around moving/renaming jenkins jobs before and after merging it.
